export const LOGIN_INTO_PAGE = "LOGIN_INTO_PAGE";
export const ERROR_WHILE_LOGGIN = "ERROR_WHILE_LOGGIN";
export const GET_ALL_USERS = "GET_ALL_USERS";

export const GET_CONVERSATIONS = "GET_CONVERSATIONS";
export const LOAD_MESSAGES = "LOAD_MESSAGES";

export const SET_IS_CHAT_STATE = "SET_IS_CHAT_STATE";

export const SEND_NEW_MESSAGE = "SEND_NEW_MESSAGE";

export const SET_IS_SETTINGS_STATE = "SET_IS_SETTINGS_STATE";

export const LOGOUT_USER = "LOGOUT_USER";

export const SET_ARRIVAL_MESSAGE = "SET_ARRIVAL_MESSAGE";

export const GET_ARRIVAL_MESSAGE = "GET_ARRIVAL_MESSAGE";

export const SET_SEARCH_INPUT = "SET_SEARCH_INPUT";

export const REGISTRATION = "REGISTRATION";
